### ISSUE TITLE
✨ [FEAT] 수강신청 대기열 삽입

### ISSUE THREAD

**Issue by yeon2lee** [2024Hanium-Allclear/Waiting#4]
## 📝 개요
- 수강신청 시, SQS를 이용하여 사용자 요청을 대기열에 삽입

## ✔️ To-Do
- [ ] Amazon SQS 환경설정
- [ ] SQS 메세지 발신
- [ ] SQS 메세지 수신

## 👀 ETC
- 참고자료 등 기타 내용 작성

## ⏰ 예상 소요 시간
- 8월 31일까지 완료 예정
